name: Run Python Script Every 2 Minutes

on:
  schedule:
    - cron: "*/2 * * * *"  # Runs every 2 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: pip install -r requirements.txt || echo "No dependencies"

      - name: Run Python Script
        run: python AutomaticWOUpload.py  # script filename
